[package]
name = "dependency_graph"
version = "0.1.0"
authors = ["Guillaume Chérel <guillaume.cherel@iscpif.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.10"
